# Copyright Contributors to the KubeOpenCode project
# EventBus provides the event transport layer for Argo Events.
# This uses NATS JetStream for reliable event delivery with
# exactly-once semantics, replacing the deprecated NATS Streaming.
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
spec:
  jetstream:
    version: "2.10.29"
    replicas: 3
